/*
 ** Copyright (c) 2026 Oracle and/or its affiliates.
 **
 ** The Universal Permissive License (UPL), Version 1.0
 **
 ** Subject to the condition set forth below, permission is hereby granted to any
 ** person obtaining a copy of this software, associated documentation and/or data
 ** (collectively the "Software"), free of charge and under any and all copyright
 ** rights in the Software, and any and all patent rights owned or freely
 ** licensable by each licensor hereunder covering either (i) the unmodified
 ** Software as contributed to or provided by such licensor, or (ii) the Larger
 ** Works (as defined below), to deal in both
 **
 ** (a) the Software, and
 ** (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
 ** one is included with the Software (each a "Larger Work" to which the Software
 ** is contributed by such licensors),
 **
 ** without restriction, including without limitation the rights to copy, create
 ** derivative works of, display, perform, and distribute the Software and make,
 ** use, sell, offer for sale, import, export, have made, and have sold the
 ** Software and the Larger Work(s), and to sublicense the foregoing rights on
 ** either these or other terms.
 **
 ** This license is subject to the following condition:
 ** The above copyright notice and either this complete permission notice or at
 ** a minimum a reference to the UPL must be included in all copies or
 ** substantial portions of the Software.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 ** AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 ** LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 ** OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 ** SOFTWARE.
 */

package oracle.jdbc.provider.oauth;

import com.sun.net.httpserver.HttpExchange;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.ServerSocket;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import static java.util.concurrent.TimeUnit.SECONDS;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Verifies {@link RedirectServer} with actual HTTP requests. A local HTTP
 * redirect is a network protocol, so using {@link HttpURLConnection} verifies
 * the public behavior that callers rely on without mocks or implementation
 * access.
 *
 * @implNote This code was initially generated by GPT 5.5, and then tinkered
 * on by a human.
 */
public class RedirectServerTest {

  static {
    System.setProperty("java.awt.headless", "true");
  }

  /**
   * Fake URI that the RedirectServer will attempt to open in a browser, but
   * fail to do so because of the headless setting just above.
   */
  private static final URI AUTHORIZATION_URI =
    createURI(1977, "/oauth/v1/authorize/");

  /**
   * Timeout for async operations in this test.
   */
  private final int TIMEOUT_SECONDS = 10;

  /**
   * Verifies that a result handler completes {@link RedirectServer#awaitResult}
   * with the value returned by the handler. This is correct because the result
   * handler represents the redirect request that carries the authorization
   * result back to the waiting application thread.
   */
  @Test
  public void testResultHandler() throws Exception {
    int port = port();
    URI baseUri = createURI(port, "/");
    ExecutorService executor = Executors.newCachedThreadPool();
    try (RedirectServer<String> server = new RedirectServer<>(baseUri)) {
      server.setResultHandler("/", exchange -> {
        respondOK(exchange, "ok");
        return exchange.getRequestURI().getRawQuery();
      });

      Future<String> getFuture =
        executor.submit(() -> sendGET(createURI(port, "/?a=b")));

      String result =
        server.awaitResult(AUTHORIZATION_URI, TIMEOUT_SECONDS, SECONDS);
      assertEquals("a=b", result);
      assertEquals("ok", getFuture.get(TIMEOUT_SECONDS, SECONDS));
    }
    finally {
      executor.shutdownNow();
    }
  }

  /**
   * Verifies that a regular handler can serve an intermediate request without
   * completing {@link RedirectServer#awaitResult}. This is correct because some
   * browser-based flows need preliminary requests before the final redirect
   * produces the authorization result.
   */
  @Test
  public void testSetHandler() throws Exception {
    int port = port();
    URI baseUri = createURI(port, "");
    ExecutorService executor = Executors.newCachedThreadPool();
    try (RedirectServer<String> server = new RedirectServer<>(baseUri)) {

      server.setHandler("/ping", exchange -> respondOK(exchange, "pong"));

      server.setResultHandler("/done", exchange -> {
        respondOK(exchange, "done");
        return "done";
      });

      Future<String> resultFuture =
        executor.submit(() ->
          server.awaitResult(AUTHORIZATION_URI, TIMEOUT_SECONDS, SECONDS));
      assertFalse(resultFuture.isDone());

      Future<String> pingFuture =
        executor.submit(() -> sendGET(createURI(port, "/ping")));
      assertEquals("pong", pingFuture.get(TIMEOUT_SECONDS, SECONDS));
      assertFalse(resultFuture.isDone());

      Future<String> doneFuture =
        executor.submit(() -> sendGET(createURI(port, "/done")));
      assertEquals("done", doneFuture.get(TIMEOUT_SECONDS, SECONDS));
      assertEquals("done", resultFuture.get(TIMEOUT_SECONDS, SECONDS));
    }
    finally {
      executor.shutdownNow();
    }
  }

  @Test
  public void testTimeout() throws Exception {
    int port = port();
    URI baseUri = createURI(port, "");
    ExecutorService executor = Executors.newCachedThreadPool();
    try (RedirectServer<String> server = new RedirectServer<>(baseUri)) {

      server.setResultHandler("/", exchange -> {
        respondOK(exchange, "ok");
        return exchange.getRequestURI().getRawQuery();
      });

      IllegalStateException timeoutException =
        assertThrows(
          IllegalStateException.class,
          () -> server.awaitResult(AUTHORIZATION_URI, 1, SECONDS));

      // The intent is to make sure we're seeing the right
      // IllegalStateException, and that the message tells the user something
      // useful: "timed out", "timeout", "time out", "did not complete in time",
      // etc. This code may need to be updated if we change the error message.
      assertTrue(timeoutException.getMessage()
        .toLowerCase()
        .contains("time"));
    }
    finally {
      executor.shutdownNow();
    }
  }

  /**
   * Returns an unused local port. A test-specific port is correct because each
   * server must bind an address before the test can verify real HTTP traffic.
   */
  private static int port() throws IOException {
    try (ServerSocket socket = new ServerSocket(0)) {
      return socket.getLocalPort();
    }
  }

  /**
   * Returns a URI for the test server. Building URIs from one helper keeps all
   * requests pointed at the same loopback host and selected port.
   */
  private static URI createURI(int port, String path) {
    return URI.create("http://127.0.0.1:" + port + path);
  }

  /**
   * Sends a real HTTP GET and returns the response body. A real request is the
   * observable behavior of a browser redirect, which is what the server exists
   * to process.
   */
  private static String sendGET(URI uri)
    throws IOException {
    HttpURLConnection connection =
      (HttpURLConnection) uri.toURL().openConnection();
    connection.setConnectTimeout(5_000);
    connection.setReadTimeout(5_000);
    try (InputStream input = connection.getInputStream()) {
      ByteArrayOutputStream out = new ByteArrayOutputStream();
      byte[] buffer = new byte[256];
      for (int read; (read = input.read(buffer)) != -1; ) {
        out.write(buffer, 0, read);
      }
      return out.toString(StandardCharsets.UTF_8.name());
    }
    finally {
      connection.disconnect();
    }
  }

  /**
   * Writes an HTTP 200 response. A visible response is expected because the
   * browser should receive feedback after it reaches the local redirect server.
   */
  private static void respondOK(HttpExchange exchange, String body)
    throws IOException {
    byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
    exchange.sendResponseHeaders(200, bytes.length);
    exchange.getResponseBody().write(bytes);
  }
}