
#
#  Copyright (c) 2026 Oracle and/or its affiliates.
#
#  The Universal Permissive License (UPL), Version 1.0
#
#  Subject to the condition set forth below, permission is hereby granted to any
#  person obtaining a copy of this software, associated documentation and/or data
#  (collectively the "Software"), free of charge and under any and all copyright
#  rights in the Software, and any and all patent rights owned or freely
#  licensable by each licensor hereunder covering either (i) the unmodified
#  Software as contributed to or provided by such licensor, or (ii) the Larger
#  Works (as defined below), to deal in both
#
#  (a) the Software, and
#  (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
#  one is included with the Software (each a "Larger Work" to which the Software
#  is contributed by such licensors),
#
#  without restriction, including without limitation the rights to copy, create
#  derivative works of, display, perform, and distribute the Software and make,
#  use, sell, offer for sale, import, export, have made, and have sold the
#  Software and the Larger Work(s), and to sublicense the foregoing rights on
#  either these or other terms.
#
#  This license is subject to the following condition:
#  The above copyright notice and either this complete permission notice or at
#  a minimum a reference to the UPL must be included in all copies or
#  substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
#

# Azure AD Resource Server (JWT validation)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}

# Datasource Spring Boot auto-config (HikariCP)
spring.datasource.url=${ORACLE_JDBC_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# A wallet is required if the database uses a self-signed certificate, or
# requires client authentication during a TLS handshake (i.e, mutual TLS, or
# mTLS).
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=${ORACLE_WALLET_TRUSTSTORE}

# These properties configure Oracle JDBC to authenticate with Oracle Database
# as an OAuth 2.0 client. The client must be mapped to a databaser user, as in:
#   CREATE USER hr_app_user IDENTIFIED GLOBALLY AS
#     'AZURE_CLIENT_ID=[HRAPP_CLIENT_ID]';
# The access token provider from the ojdbc-provider-azure
# module is used to request an access token with a client credentials grant. All
# properties here, other than clientSecret, can also be set in a
# descriptor-style JDBC URL:
# (DESCRIPTION=...
#   (SECURITY=...
#     (TOKEN_AUTH=AZURE_SERVICE_PRINCIPAL)
#     (AZURE_DB_APP_ID_URI=[DB_APP_ID_URI])
#     (TENANT_ID=[TENANT_ID]))
# See: https://docs.oracle.com/en/database/oracle/oracle-database/26/jajdb/oracle/jdbc/OracleConnection.html#CONNECTION_PROPERTY_TOKEN_AUTHENTICATION
spring.datasource.hikari.data-source-properties.oracle.jdbc.clientId=${HRAPP_CLIENT_ID}
spring.datasource.hikari.data-source-properties.oracle.jdbc.clientSecret=${HRAPP_CLIENT_SECRET}
spring.datasource.hikari.data-source-properties.oracle.jdbc.tokenAuthentication=AZURE_SERVICE_PRINCIPAL
spring.datasource.hikari.data-source-properties.oracle.jdbc.tenantId=${HRAPP_TENANT_ID}
spring.datasource.hikari.data-source-properties.oracle.jdbc.azureDatabaseApplicationIdUri=${DB_APP_ID_URI}

# These properties configure Oracle JDBC to execute database operations within
# the security context of an end user of the Spring application. Oracle JDBC
# will use the hrapp OAuth 2.0 client registration to request an access token
# that authorizes the application to access the database.
spring.datasource.hikari.data-source-properties.oracle.jdbc.provider.endUserSecurityContext=ojdbc-provider-spring-end-user-security-context
spring.datasource.hikari.data-source-properties.oracle.jdbc.provider.endUserSecurityContext.registrationId=hrapp
# These optional properties can enable DATA ROLEs or set END USER CONTEXT
# attributes for all end users.
#oracle.appdatasource.securitycontextprovider.data-roles=HCM_DYNAMIC_ROLE,FINANCE_DYNAMIC_ROLE
#oracle.appdatasource.securitycontextprovider.end-user-context-attribute={"EUC.HCM":{"p1": 11,"p2":"test2"}}

# Registration for an OAuth 2.0 client that represents this Spring application.
# The client must be authorized to access Oracle Database as an APPLICATION
# IDENTITY:
#   CREATE OR REPLACE APPLICATION IDENTITY hr_app
#     MAPPED TO 'AZURE_CLIENT_ID=[HRAPP_CLIENT_ID]';
spring.security.oauth2.client.registration.hrapp.client-name=hrapp
spring.security.oauth2.client.registration.hrapp.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.hrapp.client-id=${HRAPP_CLIENT_ID}
spring.security.oauth2.client.registration.hrapp.client-secret=${HRAPP_CLIENT_SECRET}
spring.security.oauth2.client.registration.hrapp.scope=${HRAPP_SCOPE}

spring.security.oauth2.client.provider.hrapp.token-uri=${HRAPP_TOKEN_URI}
spring.security.oauth2.client.provider.hrapp.authorization-uri=${HRAPP_AUTH_URI}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
