# Global configuration
global:
  scrape_interval: 15s     # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds

# Scrape configuration
scrape_configs:
  # Job to scrape your UCP application
  - job_name: 'ucp-application'
    static_configs:
      - targets: ['localhost:8080']  # Your app's metrics endpoint
    scrape_interval: 5s              # Scrape every 5 seconds for testing
    metrics_path: '/metrics'         # Path to metrics endpoint

  # Job to scrape Prometheus itself (optional)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']  # ✅ Changed from 9090 to 9091