################################################################################
# Copyright (c) 2023 Oracle and/or its affiliates.
#
# The Universal Permissive License (UPL), Version 1.0
#
# Subject to the condition set forth below, permission is hereby granted to any
# person obtaining a copy of this software, associated documentation and/or data
# (collectively the "Software"), free of charge and under any and all copyright
# rights in the Software, and any and all patent rights owned or freely
# licensable by each licensor hereunder covering either (i) the unmodified
# Software as contributed to or provided by such licensor, or (ii) the Larger
# Works (as defined below), to deal in both
#
# (a) the Software, and
# (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
# one is included with the Software (each a "Larger Work" to which the Software
# is contributed by such licensors),
#
# without restriction, including without limitation the rights to copy, create
# derivative works of, display, perform, and distribute the Software and make,
# use, sell, offer for sale, import, export, have made, and have sold the
# Software and the Larger Work(s), and to sublicense the foregoing rights on
# either these or other terms.
#
# This license is subject to the following condition:
# The above copyright notice and either this complete permission notice or at
# a minimum a reference to the UPL must be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
################################################################################

# An example of a connection properties file that configures Oracle JDBC to
# login using an OAuth access token issued by Azure's Active Directory service.
#
# This file can be located by Oracle JDBC using the "oracle.jdbc.config.file"
# connection property. For details, see:
# https://docs.oracle.com/en/database/oracle/oracle-database/23/jajdb/oracle/jdbc/OracleConnection.html#CONNECTION_PROPERTY_CONFIG_FILE

# The oracle.jdbc.provider.accessToken property needs to be configured as 
# the value seen below. This property enables the Oracle JDBC to use the
# Azure Access Token Provider.
oracle.jdbc.provider.accessToken=ojdbc-provider-azure-token

# The scope property needs to identify an application that represents
# Oracle Database. The scope is composed of the application ID URI of
# from the database's App Registration, followed by the name of a scope
# or ".default".
# The value of this property is described here:
# https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc
# And the registration of a database application is described here:
# https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/registering-oracle-database-instance-microsoft-entra-id-tenancy.html
oracle.jdbc.provider.accessToken.scope=https://example.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/.default

# The authenticationMethod property is optional in most cases. If this
# property is not configured, a provider will try each non-interactive
# authentication method until one succeeds:
# 1. service-principal
# 2. password
# 3. managed-identity
# In addition to the values listed above, this property can be set to one
# of the following values to use an interactive method: interactive or device-code
# These values are described here: 
# https://github.com/oracle/ojdbc-extensions/tree/main/ojdbc-provider-azure#configuring-authentication-for-resource-providers
# oracle.jdbc.provider.accessToken.authenticationMethod=interactive

# The tenantId property will override the AZURE_TENANT_ID environment variable. 
# If the environment variable is not set, this property needs to be configured
# for service-principal and password authentication. 
# The value of this property is described here:
# https://learn.microsoft.com/en-us/entra/fundamentals/how-to-find-tenant
# oracle.jdbc.provider.accessToken.tenantId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# The clientId property will override the AZURE_CLIENT_ID environment variable. 
# If that environment variable is not set, this property needs to be configured
# for service-principal and password authentication. For managed-identity 
# authentication, this property can be used to authenticate as a user assigned 
# managed identity.
# The value of this property is the Application (client) ID from an App Registration
# as described here:
# https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols#app-registration
# oracle.jdbc.provider.accessToken.clientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# The clientCertificatePath property will override the AZURE_CLIENT_CERTIFICATE_PATH 
# environment variable. 
# If that environment variable is not set, this property needs to be configured
# for service-principal authentication, unless a client secret is being used instead.
# The value of this property is the file system path of a certificate file
# as described here:
# https://learn.microsoft.com/en-us/entra/identity-platform/howto-create-service-principal-portal#option-1-recommended-upload-a-trusted-certificate-issued-by-a-certificate-authority
# oracle.jdbc.provider.accessToken.clientCertificatePath=/path/to/certificate.pem

# The clientCertificatePassword property will override the AZURE_CLIENT_CERTIFICATE_PASSWORD 
# environment variable. 
# If that environment variable is not set, this property needs to be configured
# for service-principal authentication if a PFX certificate is used. This property is
# not required if a PEM certificate is used, or if a client secret is used instead of
# a certificate.
# The value of this property is the password used to protect a PFX certificate file
# located by the clientCertificatePath property (above) or the 
# AZURE_CLIENT_CERTIFICATE_PATH environment variable
# oracle.jdbc.provider.accessToken.clientCertificatePassword=xxxxxxxx

# The clientSecret property will override the AZURE_CLIENT_SECRET environment variable. 
# If that environment variable is not set, this property needs to be configured
# for service-principal authentication, unless a certificate is used instead.
# The value of this property is a client secret from an App registration, as
# described here:
# https://learn.microsoft.com/en-us/entra/identity-platform/howto-create-service-principal-portal#option-3-create-a-new-client-secret
# oracle.jdbc.provider.accessToken.clientSecret=xxxxxxxx

# The username property will override the AZURE_USERNAME environment variable. 
# If that environment variable is not set, this property needs to be configured
# for password authentication.
# The value of this property is the username of an Azure account.
# oracle.jdbc.provider.accessToken.username=xxxxxxxx

# The password property will override the AZURE_PASSWORD environment variable. 
# If that environment variable is not set, this property needs to be configured
# for password authentication.
# The value of this property is the password of an Azure account identified by the
# username property or AZURE_USERNAME environment variable.
# oracle.jdbc.provider.accessToken.password=xxxxxxxx

# The redirectUri property only needs to be configured for interactive authentication.
# If it is not configured, a provider will use any available port on http://localhost
# by default.
# The value of this property is a redirect URL which has been added to an App 
# registration, as described here:
# https://learn.microsoft.com/en-us/entra/identity-platform/reply-url
# oracle.jdbc.provider.accessToken.redirectUri=http://localhost:8080
