package oracle.provider.gcp;

public enum GcpTestProperty {

  GCP_PKCS12_TLS_WALLET_SECRET_VERSION_NAME,

  GCP_PKCS12_TLS_WALLET_PASSWORD,

  GCP_SSO_TLS_WALLET_SECRET_VERSION_NAME,

  GCP_PEM_TLS_WALLET_SECRET_VERSION_NAME,

  GCP_PEM_TLS_WALLET_PASSWORD,

  GCP_CORRUPTED_TLS_WALLET_SECRET_VERSION_NAME,

  SECRET_VERSION_NAME,

  GCP_PKCS12_SEPS_SECRET_VERSION_NAME,

  GCP_PKCS12_SEPS_WALLET_PASSWORD,

  GCP_SEPS_CONNECTION_STRING_INDEX,

  GCP_SSO_SEPS_SECRET_VERSION_NAME,

  GCP_CORRUPTED_SEPS_WALLET_SECRET_VERSION_NAME;

}
