package oracle.provider.gcp;

public enum GcpTestProperty {

  GCP_PKCS12_TLS_WALLET_SECRET_VERSION_NAME,

  GCP_PKCS12_TLS_WALLET_PASSWORD,

  GCP_SSO_TLS_WALLET_SECRET_VERSION_NAME,

  GCP_PEM_TLS_WALLET_SECRET_VERSION_NAME,

  GCP_PEM_TLS_WALLET_PASSWORD,

  GCP_CORRUPTED_TLS_WALLET_SECRET_VERSION_NAME,

  SECRET_VERSION_NAME

}
