/*
 ** Copyright (c) 2025 Oracle and/or its affiliates.
 **
 ** The Universal Permissive License (UPL), Version 1.0
 **
 ** Subject to the condition set forth below, permission is hereby granted to any
 ** person obtaining a copy of this software, associated documentation and/or data
 ** (collectively the "Software"), free of charge and under any and all copyright
 ** rights in the Software, and any and all patent rights owned or freely
 ** licensable by each licensor hereunder covering either (i) the unmodified
 ** Software as contributed to or provided by such licensor, or (ii) the Larger
 ** Works (as defined below), to deal in both
 **
 ** (a) the Software, and
 ** (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
 ** one is included with the Software (each a "Larger Work" to which the Software
 ** is contributed by such licensors),
 **
 ** without restriction, including without limitation the rights to copy, create
 ** derivative works of, display, perform, and distribute the Software and make,
 ** use, sell, offer for sale, import, export, have made, and have sold the
 ** Software and the Larger Work(s), and to sublicense the foregoing rights on
 ** either these or other terms.
 **
 ** This license is subject to the following condition:
 ** The above copyright notice and either this complete permission notice or at
 ** a minimum a reference to the UPL must be included in all copies or
 ** substantial portions of the Software.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 ** AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 ** LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 ** OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 ** SOFTWARE.
 */

package oracle.jdbc.provider.hashicorp.hcpvaultsecret.authentication;

import oracle.jdbc.provider.parameter.ParameterSet;
import oracle.jdbc.provider.parameter.ParameterSetBuilder;

import static oracle.jdbc.provider.hashicorp.hcpvaultsecret.authentication.HcpVaultTokenFactory.*;

/**
 * Enumeration of authentication methods supported by HCP Vault Secrets.
 * <p>
 * This represents the different ways to authenticate with the HCP Vault Secrets API.
 * </p>
 */
public enum HcpVaultAuthenticationMethod {

  /**
   * Authentication using client credentials via the OAuth2 client_credentials flow.
   * <p>
   * This method requires the following:
   * </p>
   * <ul>
   *   <li>A <b>Client ID</b> provided by the HCP Vault console or associated
   *      with an HCP Service Principal.
   *   </li>
   *   <li>A <b>Client Secret</b> corresponding to the Client ID, ensuring
   *   secure access.
   *   </li>
   * </ul>
   * <p>
   * By using these credentials, the method retrieves a short-lived API token
   * by calling the HCP OAuth2 endpoint.
   * </p>
   */
  CLIENT_CREDENTIALS{
    @Override
    public HcpVaultSecretToken generateToken(ParameterSet parameterSet) {
      String clientId = parameterSet.getRequiredWithFallback(
              HCP_CLIENT_ID, ENV_HCP_CLIENT_ID);
      String clientSecret = parameterSet.getRequiredWithFallback(
              HCP_CLIENT_SECRET, ENV_HCP_CLIENT_SECRET);

      String rawToken = HcpVaultOAuthClient.fetchHcpAccessToken(clientId, clientSecret);
      return new HcpVaultSecretToken(rawToken);
    }

    @Override
    public ParameterSet generateCacheKey(ParameterSet parameterSet) {
      ParameterSetBuilder keyBuilder = ParameterSet.builder();

      String clientId = parameterSet.getRequiredWithFallback(
              HCP_CLIENT_ID, ENV_HCP_CLIENT_ID);
      keyBuilder.add(ENV_HCP_CLIENT_ID, HCP_CLIENT_ID, clientId);

      String clientSecret = parameterSet.getRequiredWithFallback(
              HCP_CLIENT_SECRET, ENV_HCP_CLIENT_SECRET);
      keyBuilder.add(ENV_HCP_CLIENT_SECRET, HCP_CLIENT_SECRET, clientSecret);

      return keyBuilder.build();
    }
  },

  /**
   * Authentication using the credentials file generated by the HCP CLI.
   * <p>
   * This method retrieves an access token from the standard CLI-generated
   * credentials file located at
   * <code>System.getProperty("user.home") + "/.config/hcp/creds-cache.json"</code>.
   * If the token is expired,
   * it will be automatically refreshed using the stored refresh token.
   * </p>
   * <p>
   * The credentials file must follow the standard JSON structure containing:
   * </p>
   * <pre>
   * {
   *   "login": {
   *     "access_token": "...",
   *     "refresh_token": "...",
   *     "access_token_expiry": "..."
   *   }
   * }
   * </pre>
   * <p>
   * The user can provide a custom path to the credentials file if needed.
   * </p>
   */
  CLI_CREDENTIALS_FILE{
    @Override
    public HcpVaultSecretToken generateToken(ParameterSet parameterSet) {
      try {
        String credentialsFile = parameterSet.getOptionalWithFallback(
                HCP_CREDENTIALS_FILE, ENV_HCP_CREDENTIALS_FILE, DEFAULT_CREDENTIALS_FILE_PATH);

        HcpVaultCredentialsFileAuthenticator fileAuthenticator =
                new HcpVaultCredentialsFileAuthenticator(credentialsFile);
        String token = fileAuthenticator.getValidAccessToken();
        return new HcpVaultSecretToken(token);
      } catch (Exception e) {
        throw new IllegalStateException("Failed to authenticate using HCP CLI credentials file", e);
      }
    }

    @Override
    public ParameterSet generateCacheKey(ParameterSet parameterSet) {
      ParameterSetBuilder keyBuilder = ParameterSet.builder();

      String credentialsFile = parameterSet.getOptionalWithFallback(
              HCP_CREDENTIALS_FILE, ENV_HCP_CREDENTIALS_FILE,
              DEFAULT_CREDENTIALS_FILE_PATH);

       keyBuilder.add(ENV_HCP_CREDENTIALS_FILE, HCP_CREDENTIALS_FILE, credentialsFile);

      return keyBuilder.build();
    }
  },

  /**
   * Automatically selects the best authentication method based on available parameters.
   *
   * <p>Priority order:</p>
   * <ol>
   *   <li>Uses the credentials file if present and valid.</li>
   *   <li>Falls back to client credentials authentication.</li>
   * </ol>
   */
  AUTO_DETECT{
    @Override
    public HcpVaultSecretToken generateToken(ParameterSet parameterSet) {
      IllegalStateException previousFailure;

      // 1. Try CLI_CREDENTIALS_FILE authentication first
      try {
        return CLI_CREDENTIALS_FILE.generateToken(parameterSet);
      } catch (RuntimeException fileAuthFailed) {
        previousFailure = new IllegalStateException(
                "Failed to authenticate using credentials file", fileAuthFailed);
      }

      // 2. If that fails, try CLIENT_CREDENTIALS
      try {
        return CLIENT_CREDENTIALS.generateToken(parameterSet);
      } catch (RuntimeException clientAuthFailed) {
        previousFailure.addSuppressed(new IllegalStateException(
                "Failed to authenticate using client credentials", clientAuthFailed));
      }

      // 3. If all methods fail, throw an error
      throw previousFailure;
    }

    @Override
    public ParameterSet generateCacheKey(ParameterSet parameterSet) {
      ParameterSetBuilder keyBuilder = ParameterSet.builder();

      // Include credentials file path in cache key if specified
      try {
        String credentialsFile = parameterSet.getOptionalWithFallback(
                HCP_CREDENTIALS_FILE, ENV_HCP_CREDENTIALS_FILE,
                DEFAULT_CREDENTIALS_FILE_PATH);

        keyBuilder.add(ENV_HCP_CREDENTIALS_FILE, HCP_CREDENTIALS_FILE, credentialsFile);

      } catch (Exception ignored) {}

      // Include client credentials in cache key if specified
      try {
        String clientId = parameterSet.getRequiredWithFallback(
                HCP_CLIENT_ID, ENV_HCP_CLIENT_ID);
        String clientSecret = parameterSet.getRequiredWithFallback(
                HCP_CLIENT_SECRET, ENV_HCP_CLIENT_SECRET
        );
        keyBuilder.add(ENV_HCP_CLIENT_ID, HCP_CLIENT_ID, clientId);
        keyBuilder.add(ENV_HCP_CLIENT_SECRET, HCP_CLIENT_SECRET, clientSecret);
      } catch (Exception ignored) {}

      return keyBuilder.build();
    }
  };

  // Common constants for System Properties and environment variable names
  private static final String ENV_HCP_CLIENT_ID = "HCP_CLIENT_ID";
  private static final String ENV_HCP_CLIENT_SECRET = "HCP_CLIENT_SECRET";
  private static final String ENV_HCP_CREDENTIALS_FILE = "HCP_CREDENTIALS_FILE";

  // Default values
  private static final String DEFAULT_CREDENTIALS_FILE_PATH =
          System.getProperty("user.home") + "/.config/hcp/creds-cache.json";

  /**
   * Generates a token for the authentication method.
   *
   * @param parameterSet the set of parameters for the request.
   * @return the generated token.
   */
  public abstract HcpVaultSecretToken generateToken(ParameterSet parameterSet);

  /**
   * Generates a cache key for the authentication method based on the provided parameters.
   *
   * @param parameterSet the set of parameters for the request.
   * @return a ParameterSet to be used as a cache key.
   */
  public abstract ParameterSet generateCacheKey(ParameterSet parameterSet);
}
