name: Macaron check-github-actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch:
  schedule:
    - cron: "20 15 * * 3"

permissions:
  contents: read

jobs:
  macaron-check-github-actions:
    name: Macaron policy verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@<FULL_COMMIT_SHA>
        with:
          persist-credentials: false

      - name: Run Macaron check-github-actions policy
        uses: oracle/macaron@<FULL_COMMIT_SHA>
        with:
          repo_path: https://github.com/${{ github.repository }}
          policy_file: check-github-actions
          policy_purl: pkg:github/${{ github.repository }}@${{ github.sha }}